FROM node:18.12.0
# Installing libvips-dev for sharp Compatibility
# RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev git
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}



ARG APP_KEYS=kSgPEHp5urnhiE+hiu7c4A==,HBhEiXrbfaf3aoEoCDTv1A==,oyWpNz/vA2EOdT7ULmLORQ==,S9OPs36TsLrt1WSjnqrI3A==
ARG API_TOKEN_SALT=Q93qXSvsCONMxvHw1a0VPQ==
ARG ADMIN_JWT_SECRET=jsDi9oftP0NbdM0uoGVinA==
ARG JWT_SECRET=OI+qLIzMqx5EUZvJTENRhw==
ARG DATABASE_HOST=localhost
ARG DATABASE_PORT=3306
ARG DATABASE_USER=root
ARG DATABASE_PASSWORD=password
ARG DATABASE_NAME=card
ARG DATABASE_CLIENT=sqlite

ENV APP_KEYS=${APP_KEYS}
ENV API_TOKEN_SALT=${API_TOKEN_SALT}
ENV ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
ENV JWT_SECRET=${JWT_SECRET}
ENV DATABASE_HOST=${DATABASE_HOST}
ENV DATABASE_PORT=${DATABASE_PORT}
ENV DATABASE_USER=${DATABASE_USER}
ENV DATABASE_PASSWORD=${DATABASE_PASSWORD}
ENV DATABASE_NAME=${DATABASE_NAME}

ENV DATABASE_CLIENT=${DATABASE_CLIENT}


ARG CF_ENDPOINT=""
ARG CF_ACCESS_KEY_ID=""
ARG CF_ACCESS_SECRET=""
ARG CF_BUCKET=""
ARG CF_PUBLIC_ACCESS_URL=""
ARG CF_TOKEN_VALUE=""
ARG CF_ENDPOINT_ABS=""


ENV CF_ENDPOINT=${CF_ENDPOINT}
ENV CF_ACCESS_KEY_ID=${CF_ACCESS_KEY_ID}
ENV CF_ACCESS_SECRET=${CF_ACCESS_SECRET}
ENV CF_BUCKET=$docker{CF_BUCKET}
ENV CF_PUBLIC_ACCESS_URL=${CF_PUBLIC_ACCESS_URL}
ENV CF_TOKEN_VALUE=${CF_TOKEN_VALUE}
ENV CF_ENDPOINT_ABS=${CF_ENDPOINT_ABS}


WORKDIR /opt/
# RUN npm install -g yarn
COPY package.json ./
RUN yarn global add node-gyp
# RUN rm -r node_modules
RUN yarn config set network-timeout 600000 -g && yarn install

ENV PATH /opt/node_modules/.bin:$PATH

WORKDIR /opt/app
COPY . .
RUN chown -R node:node /opt/app
# USER node
RUN ["yarn", "build"]
EXPOSE 1337
CMD ["yarn", "start"]
